BEST_ALPHA = 0.30

BEST_BETA = 0.000322

TEAM_ID_MAP = {
    "Algeria": 966,
    "Argentina": 346,
    "Australia": 328,
    "Austria": 324,
    "Belgium": 339,
    "Bosnia and Herzegovina": 768,
    "Brazil": 409,
    "Cabo Verde": 2555,
    "Canada": 1160,
    "Colombia": 408,
    "Croatia": 337,
    "Curacao": 10649,
    "Czechia": 332,
    "DR Congo": 960,
    "Ecuador": 419,
    "Egypt": 944,
    "England": 345,
    "France": 341,
    "Germany": 336,
    "Ghana": 965,
    "Haiti": 2693,
    "Iran": 1293,
    "Iraq": 2374,
    "Ivory Coast": 973,
    "Japan": 986,
    "Jordan": 1489,
    "Mexico": 972,
    "Morocco": 495,
    "Netherlands": 335,
    "New Zealand": 1918,
    "Norway": 334,
    "Panama": 2694,
    "Paraguay": 417,
    "Portugal": 340,
    "Qatar": 2379,
    "Saudi Arabia": 494,
    "Scotland": 424,
    "Senegal": 957,
    "South Africa": 485,
    "South Korea": 1159,
    "Spain": 338,
    "Sweden": 344,
    "Switzerland": 423,
    "Tunisia": 959,
    "Turkiye": 333,
    "USA": 461,
    "Uruguay": 967,
    "Uzbekistan": 1563,
}

COUNTRY_TO_CODE_MAP = {
    # Group A
    "mexico": "MEX",
    "south africa": "RSA",
    "south korea": "KOR",
    "republic of korea": "KOR",
    "korea republic": "KOR",
    "czech republic": "CZE",
    "czechia": "CZE",
    # Group B
    "canada": "CAN",
    "bosnia and herzegovina": "BIH",
    "bosnia": "BIH",
    "qatar": "QAT",
    "switzerland": "SUI",
    # Group C
    "brazil": "BR",
    "morocco": "MAR",
    "haiti": "HAI",
    "scotland": "SCO",
    # Group D
    "united states": "USA",
    "usa": "USA",
    "united states of america": "USA",
    "paraguay": "PAR",
    "australia": "AUS",
    "turkey": "TUR",
    "türkiye": "TUR",
    # Group E
    "germany": "GER",
    "curaçao": "CUW",
    "curacao": "CUW",
    "ivory coast": "CIV",
    "côte d'ivoire": "CIV",
    "cote d'ivoire": "CIV",
    "ecuador": "ECU",
    # Group F
    "netherlands": "NED",
    "japan": "JPN",
    "sweden": "SWE",
    "tunisia": "TUN",
    # Group G
    "belgium": "BEL",
    "egypt": "EGY",
    "iran": "IRN",
    "ir iran": "IRN",
    "new zealand": "NZL",
    # Group H
    "spain": "ESP",
    "cape verde": "CPV",
    "cabo verde": "CPV",
    "saudi arabia": "KSA",
    "uruguay": "URU",
    # Group I
    "france": "FRA",
    "senegal": "SEN",
    "iraq": "IRQ",
    "norway": "NO",
    # Group J
    "argentina": "ARG",
    "algeria": "ALG",
    "austria": "AUT",
    "jordan": "JOR",
    # Group K
    "portugal": "POR",
    "dr congo": "COD",
    "congo dr": "COD",
    "democratic republic of congo": "COD",
    "democratic republic of the congo": "COD",
    "uzbekistan": "UZB",
    "colombia": "COL",
    # Group L
    "england": "ENG",
    "croatia": "CRO",
    "ghana": "GHA",
    "panama": "PAN",
}
